version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t .

  build:
    commands:
      - zip -r lambda_function.zip .  # Package Lambda function

artifacts:
  files:
    - lambda_function.zip
