Resources:
  SeleniumLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 1024
      Timeout: 120
      Layers:
        - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:10
      Environment:
        Variables:
          AWS_SAM_LOCAL: "true"
