AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SeleniumLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: ./package
      Timeout: 30
      MemorySize: 1024
      Environment:
        Variables:
          SELENIUM_HEADLESS: "true"
          SELENIUM_TEST_URL: "http://aws-personal-portfolio-bucket.s3-website-us-east-1.amazonaws.com"
